// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu8PhrChw_Pbhvz2Xgpp2Kf8y13kCuP2M',
    appId: '1:694415653267:web:7a28a6545af2e3cf079066',
    messagingSenderId: '694415653267',
    projectId: 'lost-and-found-126d1',
    authDomain: 'lost-and-found-126d1.firebaseapp.com',
    storageBucket: 'lost-and-found-126d1.appspot.com',
    measurementId: 'G-SFY3K5RFHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEb6XWSCP_lGAp8yJShmIbbElIX8uCcLU',
    appId: '1:694415653267:android:f08ca62b5b15aa57079066',
    messagingSenderId: '694415653267',
    projectId: 'lost-and-found-126d1',
    storageBucket: 'lost-and-found-126d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGmPyn0PMKM0XObhaUyz_4uC36UGSr9TQ',
    appId: '1:694415653267:ios:de29f886be2e019d079066',
    messagingSenderId: '694415653267',
    projectId: 'lost-and-found-126d1',
    storageBucket: 'lost-and-found-126d1.appspot.com',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGmPyn0PMKM0XObhaUyz_4uC36UGSr9TQ',
    appId: '1:694415653267:ios:711cbae839084150079066',
    messagingSenderId: '694415653267',
    projectId: 'lost-and-found-126d1',
    storageBucket: 'lost-and-found-126d1.appspot.com',
    iosBundleId: 'com.example.lostFoundApp.RunnerTests',
  );
}
